FROM node:16-alpine3.16

WORKDIR /nuxt-app

# copy the app, note .dockerignore
COPY . /nuxt-app
RUN npm install
RUN npm run build
# build necessary, even if no static files are needed,
# since it builds the server as well
#RUN npm run build

# expose 5000 on container
EXPOSE 3500

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=3500

# start the app
CMD [ "npm", "run","start" ]